INSERT INTO currencies(code,descs)
VALUES
('AED','Emirati Dirham'),
('ARS','Argentine Peso'),
('AUD','Australian Dollar'),
('BGN','Bulgarian Lev'),
('BHD','Bahraini Dinar'),
('BND','Bruneian Dollar'),
('BRL','Brazilian Real'),
('BWP','Botswana Pula'),
('CAD','Canadian Dollar'),
('CHF','Swiss Franc'),
('CLP','Chilean Peso'),
('CNY','Chinese Yuan Renminbi'),
('COP','Colombian Peso'),
('CZK','Czech Koruna'),
('DKK','Danish Krone'),
('EUR','Euro'),
('GBP','British Pound'),
('HKD','Hong Kong Dollar'),
('HRK','Croatian Kuna'),
('HUF','Hungarian Forint'),
('IDR','Indonesian Rupiah'),
('ILS','Israeli Shekel'),
('INR','Indian Rial'),
('ISK','Icelandic Krona'),
('JPY','Japanese Yen'),
('KRW','South Korean Won'),
('KWD','Kuwaiti Dinar'),
('KZT','Kazakhstani Tenge'),
('LKR','Sri Lankan Rupee'),
('LYD','Libyan Dinar'),
('MUR','Mauritian Rupee'),
('MXN','Mexican Peso'),
('MYR','Malaysian Ringgit'),
('NOK','Norwegian Krone'),
('NPR','Nepalese Rupee'),
('NZD','New Zealand Dollar'),
('OMR','Omani Rial'),
('PHP','Philippine Peso'),
('PKR','Pakistani Rupee'),
('PLN','Polish Zloty'),
('QAR','Qatari Riyal'),
('RON','Romanian New Leu'),
('RUB','Russian Ruble'),
('SAR','Saudi Arabian Riyal'),
('SEK','Swedish Krona'),
('SGD','Singapore Dollar'),
('THB','Thai Baht'),
('TRY','Turkish Lira'),
('TTD','Trinidadian Dollar'),
('TWD','Taiwan New Dollar'),
('USD','US Dollar'),
('VEF','Venezuelan Bolivar'),
('ZAR','South African Rand');

INSERT INTO indices(code,descs)
VALUES
('%5EGSPC','S&P 500'),
('%5EDJI','Dow Jones Industrial Average'),
('%5EIXIC','NASDAQ Composite'),
('%5ENYA','NYSE COMPOSITE (DJ)'),
('%5EXAX','NYSE AMEX COMPOSITE INDEX'),
('%5EBUK100P','Cboe UK 100 Price Return'),
('%5ERUT','Russell 2000'),
('%5EVIX','Vix'),
('%5EFTSE','FTSE 100'),
('%5EGDAXI','DAX PERFORMANCE-INDEX'),
('%5EFCHI','CAC 40'),
('%5ESTOXX50E','ESTX 50 PR.EUR'),
('%5EN100','EURONEXT 100'),
('%5EBFX','BEL 20'),
('IMOEX.ME','MOEX Russia Index'),
('%5EN225','Nikkei 225'),
('%5EHSI','HANG SENG INDEX'),
('000001.SS','SSE Composite Index'),
('%5ESTI','STI Index'),
('%5EAXJO','S&P/ASX 200'),
('%5EAORD','ALL ORDINARIES'),
('%5EBSESN','S&P BSE SENSEX'),
('%5EJKSE','Jakarta Composite Index'),
('%5EKLSE','FTSE Bursa Malaysia KLCI'),
('%5ENZ50','S&P/NZX 50 INDEX GROSS'),
('%5EKS11','KOSPI Composite Index'),
('%5ETWII','TSEC weighted index'),
('%5EGSPTSE','S&P/TSX Composite index'),
('%5EBVSP','IBOVESPA'),
('%5EMXX','IPC MEXICO'),
('%5EIPSA','S&P/CLX IPSA'),
('%5EMERV','MERVAL'),
('%5ETA125.TA','TA-125'),
('%5ECASE30','EGX 30 Price Return Index'),
('%5EJN0U.JO','Top 40 USD Net TRI Index');